apiVersion: v1
kind: Service
metadata:
  name: system-monitoring-service
spec:
  selector:
    app: system-monitoring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
